
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA COMPARACION FIN ID IF IGUAL IMPRIMIR INICIO LLAVEDER LLAVEIZQ NUMERO PARENDER PARENIZQ PROCESO PUNTOYCOMA STRINGprograma : INICIO PUNTOYCOMA declaraciones FIN PUNTOYCOMAdeclaraciones : declaraciones declaracion\n                     | declaraciondeclaracion : declaracion_variable\n                   | sentenciadeclaracion_variable : CADENA ID IGUAL STRING PUNTOYCOMA\n                            | CADENA ID IGUAL NUMERO PUNTOYCOMAsentencia : sentencia_proceso\n                 | sentencia_imprimir\n                 | sentencia_ifsentencia_proceso : PROCESO PUNTOYCOMAsentencia_imprimir : IMPRIMIR STRING PUNTOYCOMAsentencia_if : IF PARENIZQ condicion PARENDER LLAVEIZQ declaraciones LLAVEDER\n                    | IF PARENIZQ condicion PARENDER LLAVEIZQ declaraciones LLAVEDER sentencia_ifcondicion : expresion COMPARACION expresionexpresion : ID\n                 | NUMERO\n                 | STRING'
    
_lr_action_items = {'INICIO':([0,],[2,]),'$end':([1,21,],[0,-1,]),'PUNTOYCOMA':([2,12,15,19,29,30,],[3,18,21,23,33,34,]),'CADENA':([3,4,5,6,7,9,10,11,16,18,23,33,34,35,37,38,39,],[8,8,-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,8,8,-13,-14,]),'PROCESO':([3,4,5,6,7,9,10,11,16,18,23,33,34,35,37,38,39,],[12,12,-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,12,12,-13,-14,]),'IMPRIMIR':([3,4,5,6,7,9,10,11,16,18,23,33,34,35,37,38,39,],[13,13,-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,13,13,-13,-14,]),'IF':([3,4,5,6,7,9,10,11,16,18,23,33,34,35,37,38,39,],[14,14,-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,14,14,14,-14,]),'FIN':([4,5,6,7,9,10,11,16,18,23,33,34,38,39,],[15,-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,-13,-14,]),'LLAVEDER':([5,6,7,9,10,11,16,18,23,33,34,37,38,39,],[-3,-4,-5,-8,-9,-10,-2,-11,-12,-6,-7,38,-13,-14,]),'ID':([8,20,32,],[17,26,26,]),'STRING':([13,20,22,32,],[19,28,29,28,]),'PARENIZQ':([14,],[20,]),'IGUAL':([17,],[22,]),'NUMERO':([20,22,32,],[27,30,27,]),'PARENDER':([24,26,27,28,36,],[31,-16,-17,-18,-15,]),'COMPARACION':([25,26,27,28,],[32,-16,-17,-18,]),'LLAVEIZQ':([31,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaraciones':([3,35,],[4,37,]),'declaracion':([3,4,35,37,],[5,16,5,16,]),'declaracion_variable':([3,4,35,37,],[6,6,6,6,]),'sentencia':([3,4,35,37,],[7,7,7,7,]),'sentencia_proceso':([3,4,35,37,],[9,9,9,9,]),'sentencia_imprimir':([3,4,35,37,],[10,10,10,10,]),'sentencia_if':([3,4,35,37,38,],[11,11,11,11,39,]),'condicion':([20,],[24,]),'expresion':([20,32,],[25,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIO PUNTOYCOMA declaraciones FIN PUNTOYCOMA','programa',5,'p_programa','app.py',64),
  ('declaraciones -> declaraciones declaracion','declaraciones',2,'p_declaraciones','app.py',68),
  ('declaraciones -> declaracion','declaraciones',1,'p_declaraciones','app.py',69),
  ('declaracion -> declaracion_variable','declaracion',1,'p_declaracion','app.py',76),
  ('declaracion -> sentencia','declaracion',1,'p_declaracion','app.py',77),
  ('declaracion_variable -> CADENA ID IGUAL STRING PUNTOYCOMA','declaracion_variable',5,'p_declaracion_variable','app.py',81),
  ('declaracion_variable -> CADENA ID IGUAL NUMERO PUNTOYCOMA','declaracion_variable',5,'p_declaracion_variable','app.py',82),
  ('sentencia -> sentencia_proceso','sentencia',1,'p_sentencia','app.py',93),
  ('sentencia -> sentencia_imprimir','sentencia',1,'p_sentencia','app.py',94),
  ('sentencia -> sentencia_if','sentencia',1,'p_sentencia','app.py',95),
  ('sentencia_proceso -> PROCESO PUNTOYCOMA','sentencia_proceso',2,'p_sentencia_proceso','app.py',99),
  ('sentencia_imprimir -> IMPRIMIR STRING PUNTOYCOMA','sentencia_imprimir',3,'p_sentencia_imprimir','app.py',103),
  ('sentencia_if -> IF PARENIZQ condicion PARENDER LLAVEIZQ declaraciones LLAVEDER','sentencia_if',7,'p_sentencia_if','app.py',107),
  ('sentencia_if -> IF PARENIZQ condicion PARENDER LLAVEIZQ declaraciones LLAVEDER sentencia_if','sentencia_if',8,'p_sentencia_if','app.py',108),
  ('condicion -> expresion COMPARACION expresion','condicion',3,'p_condicion','app.py',115),
  ('expresion -> ID','expresion',1,'p_expresion','app.py',123),
  ('expresion -> NUMERO','expresion',1,'p_expresion','app.py',124),
  ('expresion -> STRING','expresion',1,'p_expresion','app.py',125),
]
